version: '3.8'

services:
    telegram-downloader:
        image: jsavargas/telegram-downloader:develop
        container_name: telegram-downloader
        restart: unless-stopped
        environment:
            - API_ID=${API_ID}
            - API_HASH=${API_HASH}
            - BOT_TOKEN=${BOT_TOKEN}
            - AUTHORIZED_USER_ID=${AUTHORIZED_USER_ID}
            - TZ=America/Santiago
        volumes:
            - ./config:/config
            - ./download:/download
            - /path/torrent/watch:/watch
        tty: true
